name: GITHUB Actions Demo
run-name: ${{github.actor}} is testing out Github Actions
on:
  push:
    branches:
      - Karami

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o out

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: published-app
        path: ./out

    - name: Deploy to server
      run: |
        scp -i ${{ secrets.fifthkey }} -r ./out/* user@server:/var/www/html