name: CI/CD Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
    branches:
      - Karami

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust this to your required .NET version

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet publish -c Release -o output

      - name: Archive project
        run: tar -czf 9face9160847e2128dee77f10ab4f58d603a4278.tar.gz -C output .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Team002TechCO
          environment_name: Team002TechCO-env
          version_label: new-version-$(date +%s)
          region: us-east-1
          wait_for_deployment: true
          deployment_package: 9face9160847e2128dee77f10ab4f58d603a4278.tar.gz
          use_existing_version_if_available: true










  









